# ------------------------------------------------------------------------------------------------------------------- #
#                               _____               _      _  _  _    _                _____                          #
#              /\        /\    / ____|    /\       | |    | |(_)| |  (_)              |  __ \                         #
#             /  \      /  \  | |        /  \    __| |  __| | _ | |_  _   ___   _ __  | |__) |_ __  ___               #
#            / /\ \    / /\ \ | |       / /\ \  / _` | / _` || || __|| | / _ \ | '_ \ |  ___/| '__|/ _ \              #
#           / ____ \  / ____ \| |____  / ____ \| (_| || (_| || || |_ | || (_) || | | || |    | |  | (_) |             #
#          /_/    \_\/_/    \_\\_____|/_/    \_\\__,_| \__,_||_| \__||_| \___/ |_| |_||_|    |_|   \___/              #
#                                                                                                                     #
#                           __  __         _       _           ___ _        _                                         #
#                          |  \/  |__ _ __| |___  | |__ _  _  | _ \ |_  ___| |_ ___ _ _                               #
#                          | |\/| / _` / _` / -_) | '_ \ || | |  _/ ' \/ _ \  _/ _ \ ' \                              #
#                          |_|  |_\__,_\__,_\___| |_.__/\_, | |_| |_||_\___/\__\___/_||_|                             #
#                                                       |__/                                                          #
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
#                                           _      _    _ _ _   _                                                     #
#                                          /_\  __| |__| (_) |_(_)___ _ _  ___                                        #
#                                         / _ \/ _` / _` | |  _| / _ \ ' \(_-<                                        #
#                                        /_/ \_\__,_\__,_|_|\__|_\___/_||_/__/                                        #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #

# BrandHider allows you to modify the brand that is shown in the debug screen of minecraft.
# This can be useful if you want to create a custom message or just hide your actual setup.
BrandHider:
  # Do you want to enable BrandHider?
  enabled: false
  # This is the replacement text for the brand.
  # You can use the character & for color codes and all placeholders that are available in normal checks
  brand: "Some Spigot"
  # If you want to display attributes that update over time, e.g. TPS, Ping, Time or Date this will update the values
  # in the defined interval.
  # Set to 0 to disable the refreshing (recommended if you only use static text or placeholders that do not change)
  # Measured in ticks
  refresh_rate: 0

# This will spoof the health of all players on your server so that DamageIndicators (and any other mod to that tries
# to show other players' health, like HealthTags and ESP) becomes useless.
# This is a clientsided spoof, meaning that your plugins are able to get the correct health.
DamageIndicator:
  # Do you want to enable DamageIndicator?
  enabled: false
  # Spoof the health of the following entity categories.
  spoof:
    players: true
    animals: true
    monsters: true

# This automatically deletes old log files of both AAC and AACAdditionPro
# It activates automatically on restart and after that in a 12 hour cycle.
LogBot:
  # Do you want to enable LogBot?
  enabled: false
  # After how many days should AACAdditionPro logs be deleted
  # Set to -1 to disable
  AACAdditionPro: 10
  # After how many days should server logs be deleted
  # Set to -1 to disable
  Server: 10

# ------------------------------------------------------------------------------------------------------------------- #
#                                               ___ _           _                                                     #
#                                              / __| |_  ___ __| |__ ___                                              #
#                                             | (__| ' \/ -_) _| / /(_-<                                              #
#                                              \___|_||_\___\__|_\_\/__/                                              #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #


# AutoFish detects cheats that are named just like the check - automatic fishing bots which can yield a lot of
# treasure and food for those who use them.
#
# If you have modified fishing time and/or behaviour please test if this check is compatible with your setup.
# This check does only work on minecraft versions 1.11 and beyond due to changes in the spigot API compared to older
# versions and auto-disables itself accordingly.
AutoFish:
  # Do you want to enable the AutoFish check?
  enabled: true
  # This message will appear in AAC's status when AAC is used.
  aac_status_message: "[AACAdditionPro] Player has botlike fishing behaviour"
  # Violation before AACAdditionPro starts to cancel the fishing.
  # Please think of potential luck, because of this I do not recommend to set this to a value smaller than 7.
  # Set this to 0 to never cancel fishing.
  cancel_vl: 10
  # Control the different parts of AutoFish
  parts:
    # The inhuman reaction part recognizes very fast reaction speeds to detect AutoFishing mods.
    # This might cause some false positives with experienced fishers.
    # This will add up to 6 vl, depending on the reaction speed.
    inhuman_reaction:
      # Do you want to enable the inhuman reaction part?
      enabled: true
      # This message will appear in AAC's status when AAC is used.
      aac_status_message: "[AACAdditionPro] The player's fishing reaction times are inhumanly fast."
      # How many milliseconds should have passed before a fishing action counts as legit.
      # This also influences the given vl according to a linear distribution - the faster and more inhuman someone
      # reacts, the more vl they will get.
      human_reaction_time: 145
    # The consistency part recognizes unchanging times between a successful catch and fishing again as simple bots have
    # constant reaction times, whereas human players reaction varies a little bit each time they fish.
    # Depending on how accurate the consistency is players will receive between 1 and 15 vl.
    consistency:
      # Do you want to enable the consistency part?
      enabled: true
      # This message will appear in AAC's status when AAC is used.
      aac_status_message: "[AACAdditionPro] The player's fishing times are inhumanly constant."
      # How many fishing attempts should be checked by the consistency check
      fishing_attempt_count: 5
      # The minimum variation a player has to have in their reaction times to count as non cheating (in milliseconds)
      min_variation: 30
      # After how many failed attempts to fish between two successful attempts should a player be exempted from the
      # consistency part?
      #
      # This is a countermeasure for afk fishing farm false positives.
      # Do not extensively lower this value because bots with a custom fail-rate might not be detected.
      #
      # If you do not allow afk fishing farms on your server set this to 0.
      # Values
      maximum_fails: 12
  # Map of violation levels to command
  thresholds:
    8: "<YOUR_STAFFCHAT_COMMAND> {player} in {world} is suspected for AutoFish"
    12: "<YOUR_STAFFCHAT_COMMAND> {player} in {world} is highly suspected for AutoFish"
    18: "kick {player} AutoFish"


# ------------------------------------------------------------------------------------------------------------------- #
#                                            ___          _   _          _                                            #
#                                           / __| ___ _ _| |_(_)_ _  ___| |                                           #
#                                           \__ \/ -_) ' \  _| | ' \/ -_) |                                           #
#                                           |___/\___|_||_\__|_|_||_\___|_|                                           #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #


# Sentinel watches over your server detecting mods and sometimes certain cheat clients on join without false detections.
# It does so by listening for certain messages that clients and mods can send over channels invisible to the user.
# You can define your own checks in the listening section.
Sentinel:
  # If AAC's feature system is used every detection will show up as with this score in AAC's status.
  AACFeatureScore: 100

  # A popular PvP modification to enhance the sprinting behaviour (ToggleSprint)
  BetterSprinting:
    # Do you want to enable BetterSprinting-Control?
    enabled: false
    # The mod provides a method to disable it.
    # If you want to completely disable the mod set this to true.
    disable_mod: false
    # This mod provides a method to disable parts of it.
    # Disabling all subparts listed here will a BetterSprinting client behave like a vanilla client.
    # To disable a subpart set the value to true.
    # This more specific disable feature will only work on versions
    disable:
      # This gives players a configurable speed boost when flying in creative or survival mode.
      survival_fly_boost: true
      enable_all_dirs: true
    # What commands will be executed if the mod is detected.
    commands:
      - "<YOUR_STAFFCHAT_COMMAND> {player} in {world} uses BetterSprinting"

  # Here you can easily define your own simple Sentinel checks.
  # These checks are automatically generated, please make sure that you use NO SPECIAL CHARACTERS and NO DUPLICATE
  # NAMES to define a check (special characters are obviously fine as channel names and in "contains").
  #
  # Simple step-by-step manual to create your own check:
  # (1) Copy the section of PXMod
  # (2) Rename the section from PXMod to <NAME_OF_YOUR_CUSTOM_CHECK>
  # (3) Add the channels you want to listen to in incoming channels (e.g. minecraft:brand)
  #     AACAdditionPro will automatically try to generate the legacy channel name and listen for that as well (in this
  #     case MC|Brand).
  # (4) If needed, define what the message need to contain to trigger the check. E.g. if you are listening to
  #     minecraft:brand and superspecialmod:version to detect a mod you could define containsAny as:
  #     containsAll: ["SSM", "ssm"]
  #     Note: that is a purely fictional example, the channels and messages will differ for each mod, and many mods
  #     will not send any message (especially if they are used to cheat).
  # (5) Define the commands you want to execute when the mod is detected. The commands are executed exactly once right
  #     after player join. This allows you to e.g. disallow a certain mod on your server by kicking players on join.
  Custom:
    # This will detect PXMod,
    PXMod:
      # Whether or not to enable this check.
      enabled: true
      #
      incoming_channels:
        - "PX|Version"
      # All strings in this list will need to be included in the message sent in the channels above to trigger the
      # commands. An empty list defined as [ ] means any message is accepted by containsAll.
      containsAll: [ ]
      # At least one string in this list will need to be included in the message sent in the channels above to trigger
      # the commands. An empty list defined as [ ] means any message is accepted by containsAny.
      containsAny: [ ]
      # What commands will be executed if the mod is detected.
      commands:
        - "kick {player} PXMod"

# ------------------------------------------------------------------------------------------------------------------- #
#                                               ___      _                                                            #
#                                              |   \ ___| |__ _  _ __ _                                               #
#                                              | |) / -_) '_ \ || / _` |                                              #
#                                              |___/\___|_.__/\_,_\__, |                                              #
#                                                                 |___/                                               #
#                                                                                                                     #
# ------------------------------------------------------------------------------------------------------------------- #


# If this option is active and AAC is installed AACAdditionPro will not execute any commands specified above and instead
# hooks the AAC feature system to allow you to specify punishments via the AAC config.
# This way, AACAdditionPro's checks will also appear in AAC's status messages.
UseAACFeatureSystem: true

# Should players with the aac.verbose permission get the AACAdditionPro verbose messages
Debug:
  # Do you want AACAdditionPro to log into a log-file?
  file: true
  # Should players be able to get verbose messages if they have the aac.verbose permission
  # Players can toggle the verbose output with the command /aacadditionpro verbose
  players: false
  # Should the verbose output be logged in the console (very spammy, only recommended for testing purposes)
  console: false
