name: AACAdditionPro
version: ${project.version}
description: ${project.description}
author: Photon
api-version: 1.13
website: https://www.spigotmc.org/resources/aacadditionpro.33590/

depend: [ ProtocolLib ]
softdepend: [ AAC5, ViaVersion ]
main: de.photon.aacadditionpro.AACAdditionPro

commands:
  aacadditionpro:
    aliases: [ aacap, aacadp ]
    description: The main command of AACAdditionPro.
    usage: /aacadditionpro

permissions:
  aacadditionpro.*:
    description: Allows to bypass all checks and clientcontrols and gives access to all commands and the debug system.
    children:
      aacadditionpro.bypass.*: true
      aacadditionpro.debug: true
      aacadditionpro.info: true
      aacadditionpro.setvl: true
      aacadditionpro.tablistremove: true
    default: op

  aacadditionpro.bypass.*:
    description: Players with this permission will not be checked by AACAdditionPro.
    children:
      aacadditionpro.bypass.sentinel.*: true
      aacadditionpro.bypass.aacadditionpro_autoeat: true
      aacadditionpro.bypass.aacadditionpro_autofish: true
      aacadditionpro.bypass.aacadditionpro_autofish.parts.consistency: true
      aacadditionpro.bypass.aacadditionpro_autofish.parts.inhuman_reaction: true
      aacadditionpro.bypass.aacadditionpro_autopotion: true
      aacadditionpro.bypass.aacadditionpro_damageindicator: true
      aacadditionpro.bypass.aacadditionpro_esp: true
      aacadditionpro.bypass.aacadditionpro_fastswitch: true
      aacadditionpro.bypass.aacadditionpro_impossiblechat: true
      aacadditionpro.bypass.aacadditionpro_inventory: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.averageheuristic: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.hit: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.move: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.multiinteraction: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.perfectexit: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.rotation: true
      aacadditionpro.bypass.aacadditionpro_inventory.parts.sprinting: true
      aacadditionpro.bypass.aacadditionpro_packetanalysis: true
      aacadditionpro.bypass.aacadditionpro_packetanalysis.parts.animation: true
      aacadditionpro.bypass.aacadditionpro_packetanalysis.parts.equalrotation: true
      aacadditionpro.bypass.aacadditionpro_packetanalysis.parts.illegalpitch: true
      aacadditionpro.bypass.aacadditionpro_pingspoof: true
      aacadditionpro.bypass.aacadditionpro_scaffold: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.angle: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.position: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.rotation.derivative: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.rotation.fastChange: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.rotation.secondderivative: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.safewalk.type1: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.safewalk.type2: true
      aacadditionpro.bypass.aacadditionpro_scaffold.parts.sprinting: true
      aacadditionpro.bypass.aacadditionpro_skinblinker: true
      aacadditionpro.bypass.teaming: true
      aacadditionpro.bypass.tower: true

  aacadditionpro.bypass.sentinel.*:
    description: Bypasses all sentinel modules. Make sure to have a permission plugin to actually bypass all sentinel modules.

  aacadditionpro.debug:
    description: This allows the player to see highly detailed information about violations if enabled in the config.

  aacadditionpro.info:
    description: Allows requesting an overview about a player's violation levels

  aacadditionpro.setvl:
    description: Allows the player to execute a command which will set the vl of another player, usually used for testing.

  aacadditionpro.tablistremove:
    description: Allows the player to execute a command which will temporarily hide a player from another's tablist.